require:
  - rubocop-rails
  - standard

AllCops:
  NewCops: enable

  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'spec/factories/**/*'
    - Gemfile.lock
    - Guardfile
    - 'app/inputs/*_input.rb'
    - 'vendor/assets/bower_components/**/*'

Style/Documentation:
   Enabled: false

Layout/LineLength:
   Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

########################
# to be removed
########################

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false
