require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'spec/factories/**/*'
    - Gemfile.lock
    - Guardfile
    - 'app/inputs/*_input.rb'
    - 'vendor/assets/bower_components/**/*'

Style/Documentation:
   Enabled: false

Metrics/LineLength:
   Max: 120

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 20
