language: ruby
sudo: required
services:
  - postgresql
env:
 global:
   - PRONTO_PULL_REQUEST_ID=$TRAVIS_PULL_REQUEST
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
addons:
  chrome: stable
  apt:
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev
before_script:
  - npm install -g yarn
  - yarn install
  - bundle exec rake db:test:prepare
after_script:
  - if [ $PRONTO_PULL_REQUEST_ID != false ]; then bundle exec pronto run -f github_pr; fi
before_install:
  - gem install bundler
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
