version: "3.7"

services:
  kms:
    image: ghcr.io/philippks/kms:latest
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file: .env

  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres:
    name: kms-postgres
