version: '3.7'
services:
  kms:
    build:
      context: .
      target: kms
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - postgres

  development:
    build:
      context: .
      target: development
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - .:/app

  tests:
    build:
      context: .
      target: test
    env_file: .env.test
    depends_on:
      - postgres-test
    volumes:
      - .:/app

  postgres:
    image: postgres:11.5
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data/

  postgres-test:
    image: postgres:11.5
    env_file: .env.test

volumes:
  postgres:
    name: kms-postgres
