version: "3.7"

services:
  production:
    build:
      context: .
      target: production
      cache_from:
        - philippks/kms:test-latest
        - philippks/kms:latest
    image: "philippks/kms:${TAG-latest}"
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - postgres

  development:
    build:
      context: .
      target: development
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - webpacker
    volumes:
      - .:/app
      - bundle:/bundle

  webpacker:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - 3035:3035
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server

  test:
    build:
      context: .
      target: test
      cache_from:
        - philippks/kms:test-latest
    image: philippks/kms:test-latest
    env_file: .env.test
    depends_on:
      - postgres-test

  postgres:
    image: postgres:12
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data/

  postgres-test:
    image: postgres:12
    env_file: .env.test

volumes:
  postgres:
    name: kms-postgres
  bundle:
    name: kms-bundle
