version: '3.4'
services:
  web:
    build:
      context: .
      target: base
    env_file: .env
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - .:/app

  test:
    build:
      context: .
      target: test
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:11.5
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
