services:
  kms:
    image: ghcr.io/philippks/kms:latest
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file: .env

  postgres:
    image: postgres:18
    shm_size: 128mb
    volumes:
      - postgres:/var/lib/postgresql/
    env_file: .env

volumes:
  postgres:
    name: kms-postgres
