services:
  postgres:
    image: postgres:12
    env_file: .env.development
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres:
    name: kms-postgres
