default:
  receiver:
    name: "<%= ENV.fetch('INVOICE_RECEIVER_NAME') { 'Some Company' } %>"
    street: "<%= ENV.fetch('INVOICE_RECEIVER_STREET') { 'Some Street 12' } %>"
    postal_code: "<%= ENV.fetch('INVOICE_RECEIVER_POSTAL_CODE') { '1234' } %>"
    city: "<%= ENV.fetch('INVOICE_RECEIVER_CITY') { 'Somewhere' } %>"
    country_code: "<%= ENV.fetch('INVOICE_RECEIVER_COUNTRY_CODE') { 'CH' } %>"
  iban: "<%= ENV.fetch('INVOICE_IBAN') { 'CH90 1111 2222 3333 4444' } %>"
  vat_number: "<%= ENV.fetch('INVOICE_VAT_NUMBER') { 'CHE-111.999.333' } %>"
  swift: "<%= ENV.fetch('INVOICE_SWIFT') { 'ZZZZZZZZZZZZZZ' } %>"
  currency_symbol: "CHF"
  persisted_pdfs_directory: "<%= Rails.root %>/storage/invoices/"
  company_template_path: <%= ENV['INVOICE_COMPANY_TEMPLATE_PATH'] %>
  mail_footer: "<%= ENV.fetch('INVOICE_MAIL_FOOTER') { 'Freundliche Grüsse' } %>"
  wicked_pdf_options:
    page_size: 'A4'
    margin:
      top: 44.45
      bottom: 20
      left: 26
      right: 18
    dpi: 96
    footer:
      right:
  qr_bill_wicked_pdf_options:
    page_size: 'A4'
    margin:
      top: 0
      bottom: 0
      left: 0
      right: 0


test:
  iban: CH90 1337 1337 1337 1337 8
  vat_number: CHE-013.131.123
  swift: 134134 1234134 123134
  persisted_pdfs_directory: "<%= Rails.root %>/tmp/"
  company_template_path: "<%= Rails.root %>/spec/fixtures/files/invoice_template.pdf"
