# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a6966885d8169be199ffacc821cc9e4f9167ddaa26ccaad2a415554f03964a487ed093633a47ddf5420cea85b7c73d07e88ba984336b2aa8ca14007c0e98615

test:
  secret_key_base: d9f1c4aaca5cd14470c62af2215de9865ac2f76aea89afa95a4c3d4b83915dcfbae14593ea9473c04de9ee5be1fa10f4ed7a9caeac6257c165548fba6e0ec221

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
