name: Build and publish a Docker image

on:
  release:
    types: [published]
  pull_request: # for testing

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # commented for testing
      #- name: Extract version from release
      #  id: meta
      #  run: |
      #    # Get tag name from release (e.g., v1.0.0)
      #    TAG_NAME="${{ github.event.release.tag_name }}"
      #    # Remove 'v' prefix if present
      #    VERSION=${TAG_NAME#v}
      #    echo "version=$VERSION" >> $GITHUB_OUTPUT
      #    echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
